name: Tests Nuget Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-nuget-packages:
    name: Nuget Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 5 (On Mac)
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
        env:
          DOTNET_INSTALL_DIR: /users/runner/alternate/dotnet
      - name: Setup .NET Core 5 (Not on mac)
        if: ${{ matrix.os != 'macos-latest' }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Cache drivers
        uses: actions/cache@v2
        with:
          path: ./src/Playwright/runtimes/
          key: ${{ hashFiles('./src/Playwright/Playwright.csproj') }}
      - name: Download Drivers
        run: dotnet run -p ./src/tools/Playwright.Tooling/Playwright.Tooling.csproj -- download-drivers --basepath .
      - name: Build Project
        run: dotnet build ./src/Playwright/Playwright.csproj -c Debug
      - name: Delete browsers on Mac
        if: matrix.os == 'macos-latest'
        run: rm -r ~/Library/Caches/ms-playwright
      - name: Delete browsers on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: rm -r ~/.cache/ms-playwright
      - name: Delete browsers on windows
        if: matrix.os == 'windows-latest'
        run: Remove-Item -path $env:USERPROFILE\AppData\Local\ms-playwright -recurse
      - name: Run Tests
        run: dotnet test ./src/Playwright.LocalNugetTest/Playwright.LocalNugetTest.csproj
