name: NuGet Package Smoke Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-nuget-packages:
    name: Nuget Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install prerequisites and download drivers
        shell: pwsh
        run: .\build.ps1 driver -prereqs
      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI
      - name: Build NUnit Package
        run: dotnet build -c Debug ./src/Playwright.NUnit/Playwright.NUnit.csproj
      - name: Generate NuGet packages 
        run: |
          dotnet pack ./src/Playwright/Playwright.csproj -c Debug -o ./src/Playwright.LocalNugetTest/nupkg
          dotnet pack ./src/Playwright.NUnit/Playwright.NUnit.csproj -c Debug -o ./src/Playwright.LocalNugetTest/nupkg
      - name: Install new NuGet Versions
        run: |
          dotnet add Playwright.LocalNugetTest.48.csproj package Microsoft.Playwright.NUnit -s ./nupkg --prerelease
          dotnet add Playwright.LocalNugetTest.50.csproj package Microsoft.Playwright.NUnit -s ./nupkg --prerelease
        working-directory: ./src/Playwright.LocalNugetTest/
      - name: Build LocalNugetTest 
        run: |
          dotnet build Playwright.LocalNugetTest.48.csproj
          dotnet build Playwright.LocalNugetTest.50.csproj
        working-directory: ./src/Playwright.LocalNugetTest/
      - name: Install Dependencies
        run: playwright install-deps
        working-directory: ./src/Playwright.LocalNugetTest/
      - name: Install Browsers
        run: playwright install
        working-directory: ./src/Playwright.LocalNugetTest/
      - name: Run Tests (net50)
        run: dotnet test Playwright.LocalNugetTest.50.csproj
        working-directory: ./src/Playwright.LocalNugetTest/
      - name: Run Tests (net48)
        run: dotnet test Playwright.LocalNugetTest.48.csproj
        working-directory: ./src/Playwright.LocalNugetTest/
