name: Nuget

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    name: Push to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Download Drivers
        run: dotnet run -p ./src/tools/Playwright.Tooling/Playwright.Tooling.csproj -- download-drivers --basepath .
      - name: Publish Playwright Sharp
        id: publish_nuget_playwright_sharp
        uses: rohith/publish-nuget@v2
        with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PROJECT_FILE_PATH: src/PlaywrightSharp/PlaywrightSharp.csproj
          VERSION_FILE_PATH: src/Common/PackageInfo.props
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          INCLUDE_SYMBOLS: false
          TAG_COMMIT: false
      - name: Publish Playwright Sharp Tools
        id: publish_nuget_playwright_sharp_tools
        uses: rohith/publish-nuget@v2
        with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PROJECT_FILE_PATH: src/tools/PlaywrightSharpTool/PlaywrightSharpTool.csproj
          VERSION_FILE_PATH: src/Common/PackageInfo.props
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          INCLUDE_SYMBOLS: false
          TAG_COMMIT: false
